configuration switches complete

diff --git a/inc/common b/inc/common
--- a/inc/common
+++ b/inc/common
@@ -9,17 +9,26 @@ config_file_path="$wp_install_path/wp-config.php"
 config_info_path="$wp_install_path/wp-info.php"
 config_override_path="$wp_install_path/wp-override.php"
 
+####
+## The only hook who should ever remove the NFS mount is the nfs-relation-(departed|broken) hook
+## Everyone else should just assume it's there or try to mount it. We don't want to loose people's
+## data, they get mad when that happens
+####
+
 make_bare()
 {
 	# Un-do APC
 	rm -f /etc/php5/conf.d/apc.ini
 	# IF there is an NFS mount, get everything out of it
-	if [ -f .nfs-mount ]; then
-		rm -f /var/www/wp-content
-		rsync -az /mnt/wordpress/wp-content /var/www/
+	if [ -f .nfs-mount ]; then # Looks like someone got fancy with NFS
+		if [ -L $wp_install_path/wp-content ]; then # Check if we actually have a symlink
+			rm -f $wp_install_path/wp-content
+			rsync -az /mnt/wordpress/wp-content $wp_install_path
+		fi
 	fi
 
 	echo "<?php" > $config_override_path
+	juju-log "We are now bare"
 }
 
 make_single()
@@ -28,6 +37,8 @@ make_single()
 	juju-log "Installing PHP apc.ini ..."
 	rm -f /etc/php5/conf.d/apc.ini
 	install -o root -g root -m 0644 files/charm/php/php5_conf.d_apc.ini /etc/php5/conf.d/apc.ini
+	make_nfs()
+	juju-log "We are now single"
 }
 
 make_optimized()
@@ -36,8 +47,8 @@ make_optimized()
 	cat > $config_override_path <<EOF
 <?php
 define('DISALLOW_FILE_MODS', TRUE);
-
 EOF
+	juju-log "We are now optimized"
 }
 
 make_nfs()
@@ -46,14 +57,19 @@ make_nfs()
 		# This has all the NFS mount stuff in it
 		source .nfs-mount
 		mkdir -p /mnt/wordpress
-		mount -t $MOUNT_TYPE -o $MOUNT_OPS $MOUNT_SERVER:/ /mnt/wordpress
-		if[ $? -ne 0 ]; then
-			juju-log "Could not connect to file-server"
-			exit 1 # OH THE HUMANITY OF IT ALL
+		if grep -qs '/mnt/wordpress' /proc/mounts; then
+			juju-log "We're already mounted."
+		else
+			mount -t $MOUNT_TYPE -o $MOUNT_OPS $MOUNT_SERVER:$MOUNT_PATH /mnt/wordpress
+			if[ $? -ne 0 ]; then
+				juju-log "Could not connect to file-server"
+				exit 1 # OH THE HUMANITY OF IT ALL
+			fi
+			rsync -az $wp_install_path/wp-content /mnt/wordpress/
+			mv $wp_install_path/wp-content $wp_install_path/wp-content.bak.$(date +%Y%m%d-%H%M%S) && rm -rf $wp_install_path/wp-content
+			ln -s /mnt/wordpress/wp-content $wp_install_path
+			juju-log "Mounted NFS"
 		fi
-		rsync -az /var/www/wp-content /mnt/wordpress/
-		mv /var/www/wp-content /var/www/wp-content.bak.$(date +%Y%m%d-%H%M%S) && rm -rf /var/www/wp-content
-		ln -s /mnt/wordpress/wp-content /var/www/
 	else
 		juju-log "There is no nfs mount, not sure what to do, so we'll just bail"
 	fi
