First revision of OMG charm

diff --git a/hooks/db-relation-changed b/hooks/db-relation-changed
--- a/hooks/db-relation-changed
+++ b/hooks/db-relation-changed
@@ -1,47 +1,66 @@
 #!/bin/bash
 
-set -eu # -x for verbose logging to juju debug-log
-
-UPLOAD_PATH="/var/www/wp-uploads"
-
+juju-log "We've got a db"
 hostname=`unit-get public-address`
+private_name=`hostname -f`
 juju-log "Retrieved hostname: $hostname"
 
 # Check we haven't already been setup.
-config_file_path="/etc/wordpress/config-$hostname.php"
-if [ -f "$config_file_path" ] ; then
-    juju-log "Wordpress for site $config_file_path already Configured, exiting"
-    echo "Already Configured, Exiting"
-    exit 0 # already setup
+wp_install_path="/var/www/omgubuntu.co.uk"
+config_file_path="$wp_install_path/wp-config.php"
+
+if [ -f "$config_file_path" ]; then
+	juju-log "OMG Ubuntu is already setup, just silently going away"
+	exit 0
 fi
 
-# Get the database settings; if not set, wait for this hook to be
-# invoked again
 database=`relation-get database`
-if [ -z "$database" ] ; then
-    exit 0 # wait for future handshake from database service unit
-fi
-
-# Our protocol on this interface ensures that all or none of the
-# settings are set. But we can verify the setting or the values if
-# more error checking if desired.
 user=`relation-get user`
 password=`relation-get password`
 host=`relation-get private-address`
 
-# Create an internal secret key for wordpress; this is unrelated to
-# the password generated for the admin user of wordpress
+if [ -z "$database" ] ; then
+    exit 0
+fi
+
 secret_key=`pwgen 10 1`
 
-juju-log "Creating appropriate upload paths and directories"
-# Setup appropriate upload paths and directories
-ln -s /usr/share/wordpress "/var/www/$hostname"
-mkdir -p $UPLOAD_PATH
-mkdir -p "$UPLOAD_PATH/$hostname"
-chown -R root:www-data $UPLOAD_PATH
-chmod 0744 $UPLOAD_PATH
-chmod 0770 "$UPLOAD_PATH/$hostname"
-chown -R root:www-data "/var/www/$hostname/wp-content"
+source "/usr/share/charm-helper/sh/net.sh"
+
+##
+# OH COME ON WORDPRESS.ORG NO VALID SSL CERTIFICATE?
+# Psh, whatever, plain-text for now. #blamenacin
+# https://twitter.com/#!/marcoceppi/status/181570187655520260
+LATEST_WORDPRESS="http://wordpress.org/latest.tar.gz"
+DOWNLOAD=`ch_get_file "$LATEST_WORDPRESS" "http://wordpress.org/latest.tar.gz.sha1"`
+##
+
+if [ ! -f "$DOWNLOAD" ] || [ -z "$DOWNLOAD" ]; then
+	juju-log "Failed to retrieve $LATEST_WORDPRESS"
+	exit 1
+fi
+
+juju-log "Extract ALL THE FILES"
+tar -xzf $DOWNLOAD
+
+juju-log "Move them in to place, but just 'drop' them in place."
+rsync -az wordpress/ $wp_install_path
+
+juju-log "Clean up"
+rm -rf wordpress
+
+juju-log "Get the last database dump"
+mkdir -p /mnt/restore/
+LATEST=`s3cmd ls s3://omgubuntu.co.uk/backups/ | tail -n 1 | awk '{ print $4 }'`
+
+juju-log "$LATEST dump"
+s3cmd $LATEST /mnt/restore/
+tar -xzf /mnt/restore/$(basename $LATEST)
+mysql -h $database -u $user -p$password $database < *.sql
+rm -f *.sql
+
+juju-log "Dropping OMG specific files: Themes, plugins, etc in to position"
+rsync -az files/wordpress/ $wp_install_path
 
 juju-log "Writing wordpress config file $config_file_path"
 # Write the wordpress config
@@ -53,44 +72,50 @@ define('DB_PASSWORD', '$password');
 define('DB_HOST', '$host');
 define('SECRET_KEY', '$secret_key');
 
-#This will disable the update notification.
-define('WP_CORE_UPDATE', false);
+define('AUTH_KEY', '$secret_key');
+define('SECURE_AUTH_KEY', '$secret_key');
+define('LOGGED_IN_KEY', '$secret_key');
+define('NONCE_KEY', '$secret_key');
 
 \$table_prefix  = 'wp_';
-\$server = '$host';
-\$loginsql = '$user';
-\$passsql = '$password';
-\$base = '$database';
-\$upload_path = '/var/www/wp-uploads/$hostname';
-\$upload_url_path = 'http://$hostname/wp-uploads';
-?>
+
 EOF
 chmod 0644 $config_file_path
 
 # Write the apache config
 # XXX a future branch will change this to use augtool
-apache_config_file_path="/etc/apache2/sites-available/$hostname"
+apache_config_file_path="/etc/apache2/sites-available/omgubuntu.co.uk"
 juju-log "Writing apache config file $apache_config_file_path"
 cat > $apache_config_file_path <<EOF
 <VirtualHost *:80>
   ServerName $hostname
-  DocumentRoot /var/www/$hostname
+  ServerAlias $private_name omgubuntu.co.uk www.omgubuntu.co.uk cdn.omgubuntu.co.uk
+  DocumentRoot $wp_install_path
   Options All
-  ErrorLog /var/log/apache2/wp-error.log
-  TransferLog /var/log/apache2/wp-access.log
-  # Store uploads in /var/www/wp-uploads/$0
-  RewriteEngine On
-  RewriteRule ^/wp-uploads/(.*)$ /var/www/wp-uploads/%%{HTTP_HOST}/\$1
+  LogLevel Warn
+  ErrorLog /var/log/apache2/omgubuntu.co.uk.error.log
+  CustomLog /var/log/apache2/omgubuntu.co.uk.access.log combined
+  
+  suPHP_UserGroup omgubuntu omgubuntu
 </VirtualHost>
 EOF
 chmod 0644 $apache_config_file_path
 
-# Configure apache
-juju-log "Enabling apache modules: rewrite, vhost_alias"
-a2enmod rewrite
-a2enmod vhost_alias
 juju-log "Enabling apache site: $hostname"
-a2ensite $hostname
+a2ensite omgubuntu.co.uk
+
+chown -R omgubuntu.omgubuntu $wp_install_path
+
+if [ ! -f /etc/cron.daily/omg-backup ]; then
+	juju-log "Put the backup process in place"
+	rsync -az files/omg-backup /etc/cron.daily/
+fi
+
+sed -i -e "s@DB_HOST=\".*\"@DB_HOST=\"$host\"@" \
+    -e "s@DB_USER=\".*\"@DB_USER=\"$user\"@" \
+    -e "s@DB_PASS=\".*\"@DB_PASS=\"$password\"@" \
+    -e "s@DB_NAME=\".*\"@DB_NAME=\"$database\"@" \
+    /etc/cron.daily/omg-backup
 
 # Restart apache
 juju-log "Restarting apache2 service"
